SRC = MaxFlops_half.cu

EXE = MaxFlops_half

metrics := smsp__cycles_active.sum,smsp__pipe_alu_cycles_active.sum,smsp__pipe_fma_cycles_active.sum,smsp__pipe_fp64_cycles_active.sum,smsp__pipe_tensor_cycles_active.sum,smsp__pipe_tensor_op_dmma_cycles_active.sum,smsp__pipe_tensor_op_hmma_cycles_active.sum,smsp__pipe_tensor_op_imma_cycles_active.sum,smsp__pipe_shared_cycles_active.sum

include ../../../common/common.mk
